services:
  # Основное Express-приложение
  app:
    build: dockerfile/app
    # restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI='mongodb://host.docker.internal:27017/minecraft'
    volumes:
      - ./:/app  # Для разработки (горячая перезагрузка)
      #- ~/.ssh/id_rsa:/root/.ssh/id_rsa.dist
    extra_hosts:
      - host.docker.internal:host-gateway
    command: "npm run dev"
#    command: "tail -f README.md"
    #tty: true
    #  - /app/node_modules  # Исключаем перезапись node_modules
    # healthcheck:  # Раскомментировать для продакшена
    #   test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3