# Используем официальный образ Node.js на Alpine Linux (маленький и безопасный)
FROM node:20-alpine

# Создаем рабочую директорию
WORKDIR /app

# Указываем порт, который будет слушать Express
EXPOSE 3000

# Запускаем приложение
CMD ["npm", "start"]